# Creación del Dataframe de Pandas y análisis

In [6]:
# Librería de Pandas
import pandas as pd

# Creación del Dataframe
data_path = '../DogRecSys/data/akc-data-latest.csv'
df = pd.read_csv(data_path, encoding='utf-8')

# Encabezado del dataframe
df_head = df.head()

# Información descriptiva (columnas, filas y tipos de datos)
df_info = df.info()

# Resumen descriptivo 
df_desc = df.describe(include='all')

# Conteo de valores nulos
df_nulos = df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 277 entries, 0 to 276
Data columns (total 21 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Unnamed: 0                   277 non-null    object
 1   description                  277 non-null    object
 2   temperament                  276 non-null    object
 3   popularity                   198 non-null    object
 4   min_height                   277 non-null    float64
 5   max_height                   277 non-null    float64
 6   min_weight                   275 non-null    float64
 7   max_weight                   275 non-null    float64
 8   min_expectancy               274 non-null    float64
 9   max_expectancy               274 non-null    float64
 10  group                        277 non-null    object
 11  grooming_frequency_value     270 non-null    float64
 12  grooming_frequency_category  270 non-null    object
 13  shedding_value               257 non-null    float64
 14  shedding_category            257 non-null    object
 15  energy_level_value           271 non-null    float64
 16  energy_level_category        271 non-null    object
 17  trainability_value           253 non-null    float64
 18  trainability_category        253 non-null    object
 19  demeanor_value               252 non-null    float64
 20  demeanor_category            252 non-null    object
dtypes: float64(11), object(10)
memory usage: 45.6+ KB

## Encabezado del Dataframe

In [7]:
df_head

,Unnamed: 0,description,temperament,popularity,min_height,max_height,min_weight,max_weight,min_expectancy,max_expectancy,...,grooming_frequency_value,grooming_frequency_category,shedding_value,shedding_category,energy_level_value,energy_level_category,trainability_value,trainability_category,demeanor_value,demeanor_category
0,Affenpinscher,The Affen’s apish look has been described many...,"Confident, Famously Funny, Fearless",148,22.86,29.21,3.175147,4.535924,12.0,15.0,...,0.6,2-3 Times a Week Brushing,0.6,Seasonal,0.6,Regular Exercise,0.8,Easy Training,1.0,Outgoing
1,Afghan Hound,"The Afghan Hound is an ancient breed, his whol...","Dignified, Profoundly Loyal, Aristocratic",113,63.50,68.58,22.679619,27.215542,12.0,15.0,...,0.8,Daily Brushing,0.2,Infrequent,0.8,Energetic,0.2,May be Stubborn,0.2,Aloof/Wary
2,Airedale Terrier,The Airedale Terrier is the largest of all ter...,"Friendly, Clever, Courageous",60,58.42,58.42,22.679619,31.751466,11.0,14.0,...,0.6,2-3 Times a Week Brushing,0.4,Occasional,0.6,Regular Exercise,1.0,Eager to Please,0.8,Friendly
3,Akita,"Akitas are burly, heavy-boned spitz-type dogs ...","Courageous, Dignified, Profoundly Loyal",47,60.96,71.12,31.751466,58.967008,10.0,13.0,...,0.8,Daily Brushing,0.6,Seasonal,0.8,Energetic,1.0,Eager to Please,0.6,Alert/Responsive
4,Alaskan Malamute,The Alaskan Malamute stands 23 to 25 inches at...,"Affectionate, Loyal, Playful",58,58.42,63.50,34.019428,38.555351,10.0,14.0,...,0.6,2-3 Times a Week Brushing,0.6,Seasonal,0.8,Energetic,0.4,Independent,0.8,Friendly

## Resumen

In [9]:
df_desc

,Unnamed: 0,description,temperament,popularity,min_height,max_height,min_weight,max_weight,min_expectancy,max_expectancy,...,grooming_frequency_value,grooming_frequency_category,shedding_value,shedding_category,energy_level_value,energy_level_category,trainability_value,trainability_category,demeanor_value,demeanor_category
count,277,277,276,198,277.000000,277.000000,275.000000,275.000000,274.000000,274.000000,...,270.000000,270,257.000000,257,271.000000,271,253.000000,253,252.000000,252
unique,277,276,267,191,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,5,NaN,5,NaN,5,NaN,5,NaN,5
top,Affenpinscher,Poodles come in three size varieties: Standard...,"Friendly, Smart, Willing to Please",7,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Weekly Brushing,NaN,Seasonal,NaN,Regular Exercise,NaN,Agreeable,NaN,Friendly
freq,1,2,3,3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,119,NaN,125,NaN,118,NaN,77,NaN,77
mean,NaN,NaN,NaN,NaN,44.225801,52.720588,17.888858,27.291416,11.306569,13.832117,...,0.425926,NaN,0.529183,NaN,0.712915,NaN,0.624506,NaN,0.620635,NaN
std,NaN,NaN,NaN,NaN,14.238298,15.885454,12.290600,19.061416,1.817949,2.016668,...,0.198306,NaN,0.189068,NaN,0.168927,NaN,0.247271,NaN,0.201713,NaN
min,NaN,NaN,NaN,NaN,12.700000,17.780000,0.000000,0.000000,0.000000,0.000000,...,0.200000,NaN,0.200000,NaN,0.200000,NaN,0.200000,NaN,0.200000,NaN
25%,NaN,NaN,NaN,NaN,33.020000,38.100000,8.164663,12.927383,10.000000,13.000000,...,0.200000,NaN,0.400000,NaN,0.600000,NaN,0.400000,NaN,0.400000,NaN
50%,NaN,NaN,NaN,NaN,45.085000,53.340000,15.875733,24.947580,12.000000,14.000000,...,0.400000,NaN,0.600000,NaN,0.600000,NaN,0.600000,NaN,0.600000,NaN
75%,NaN,NaN,NaN,NaN,55.880000,66.040000,22.679619,34.019428,12.000000,15.000000,...,0.600000,NaN,0.600000,NaN,0.800000,NaN,0.800000,NaN,0.800000,NaN
max,NaN,NaN,NaN,NaN,76.200000,88.900000,68.038855,108.862169,16.000000,19.000000,...,1.000000,NaN,1.000000,NaN,1.000000,NaN,1.000000,NaN,1.000000,NaN

## Valores nulos por columna

In [10]:
df_nulos

Unnamed: 0                      0
description                     0
temperament                     1
popularity                     79
min_height                      0
max_height                      0
min_weight                      2
max_weight                      2
min_expectancy                  3
max_expectancy                  3
group                           0
grooming_frequency_value        7
grooming_frequency_category     7
shedding_value                 20
shedding_category              20
energy_level_value              6
energy_level_category           6
trainability_value             24
trainability_category          24
demeanor_value                 25
demeanor_category              25
dtype: int64

El análisis revela que:

- El dataset contiene un conjunto de datos sobre razas de perros, con atributos tanto descriptivos (como "description", "temperament") como numéricos (como alturas, pesos, esperanza de vida, etc).
- Se detectan algunos valores nulos en columnas como "temperament", "popularity", "min_weight", "max_weight", entre otros, que se deberán revisar para el preprocesamiento previo a un entrenamiento.
- Aunque la cantidad de elementos (razas) es limitada, posee atributos que podrían darle soporte a un sistema de recomendación basado en contenido, donde las características se empleen para sugerir razas que se asemejen a las preferencias indicadas.